version: 1
disable_existing_loggers: false

formatters:
  simple:
    format: "%(asctime)s :: %(threadName)s  %(name)s - %(message)s"

handlers:
  stdout:
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout

loggers:
  root:
    level: DEBUG
    handlers:
      - stdout
